
const OPCODE = [
{id: 0x00, size: 1, name: 'Config_AppKey_Add' , process: null, callback: null},
{id: 0x01, size: 1, name: 'Config_AppKey_Update', process: null, callback: null},
{id: 0x02, size: 1, name: 'Config_Composition_Data_Status', process: Config.OUT.Composition_Data_Status, callback: null},
{id: 0x03, size: 1, name: 'Config_Model_Publication_Set', process: null, callback: null},
{id: 0x04, size: 1, name: 'Health_Current_Status', process: null, callback: null},
{id: 0x05, size: 1, name: 'Health_Fault_Status', process: null, callback: null},
{id: 0x06, size: 1, name: 'Config_Heartbeat_Publication_Status', process: null, callback: null},
{id: 0x00, size: 1, name: 'Config_AppKey_Delete_0x80', process: null, callback: null},
{id: 0x01, size: 1, name: 'Config_AppKey_Get_0x80', process: null, callback: null},
{id: 0x8002, size: 2, name: 'Config_AppKey_List', process: null, callback: null},
{id: 0x8003, size: 2, name: 'Config_AppKey_Status', process: Config.OUT.AppKey_Status, callback: null},
{id: 0x8004, size: 2, name: 'Health_Attention_Get', process: null, callback: null},
{id: 0x8005, size: 2, name: 'Health_Attention_Set', process: null, callback: null},
{id: 0x8006, size: 2, name: 'Health_Attention_Set_Unacknowledged', process: null, callback: null},
{id: 0x8007, size: 2, name: 'Health_Attention_Status', process: null, callback: null},
{id: 0x8008, size: 2, name: 'Config_Composition_Data_Get', process: null, callback: null},
{id: 0x8009, size: 2, name: 'Config_Beacon_Get', process: null, callback: null},
{id: 0x800A, size: 2, name: 'Config_Beacon_Set', process: null, callback: null},
{id: 0x800B, size: 2, name: 'Config_Beacon_Status', process: null, callback: null},
{id: 0x800C, size: 2, name: 'Config_Default_TTL_Get', process: null, callback: null},
{id: 0x800D, size: 2, name: 'Config_Default_TTL_Set', process: null, callback: null},
{id: 0x800E, size: 2, name: 'Config_Default_TTL_Status', process: null, callback: null},
{id: 0x800F, size: 2, name: 'Config_Friend_Get', process: null, callback: null},
{id: 0x8010, size: 2, name: 'Config_Friend_Set', process: null, callback: null},
{id: 0x8011, size: 2, name: 'Config_Friend_Status', process: null, callback: null},
{id: 0x8012, size: 2, name: 'Config_GATT_Proxy_Get', process: null, callback: null},
{id: 0x8013, size: 2, name: 'Config_GATT_Proxy_Set', process: null, callback: null},
{id: 0x8014, size: 2, name: 'Config_GATT_Proxy_Status', process: null, callback: null},
{id: 0x8015, size: 2, name: 'Config_Key_Refresh_Phase_Get', process: null, callback: null},
{id: 0x8016, size: 2, name: 'Config_Key_Refresh_Phase_Set', process: null, callback: null},
{id: 0x8017, size: 2, name: 'Config_Key_Refresh_Phase_Status', process: null, callback: null},
{id: 0x8018, size: 2, name: 'Config_Model_Publication_Get', process: null, callback: null},
{id: 0x8019, size: 2, name: 'Config_Model_Publication_Status', process: Config.OUT.Model_Publication_Status, callback: null},
{id: 0x801A, size: 2, name: 'Config_Model_Publication_Virtual_Address_Set', process: null, callback: null},
{id: 0x801B, size: 2, name: 'Config_Model_Subscription_Add', process: null, callback: null},
{id: 0x801C, size: 2, name: 'Config_Model_Subscription_Delete', process: null, callback: null},
{id: 0x801D, size: 2, name: 'Config_Model_Subscription_Delete_All', process: null, callback: null},
{id: 0x801E, size: 2, name: 'Config_Model_Subscription_Overwrite', process: null, callback: null},
{id: 0x801F, size: 2, name: 'Config_Model_Subscription_Status', process: Config.OUT.Model_Subscription_Status, callback: null},
{id: 0x8020, size: 2, name: 'Config_Model_Subscription_Virtual_Address_Add', process: null, callback: null},
{id: 0x8021, size: 2, name: 'Config_Model_Subscription_Virtual_Address_Delete', process: null, callback: null},
{id: 0x8022, size: 2, name: 'Config_Model_Subscription_Virtual_Address_Overwrite', process: null, callback: null},
{id: 0x8023, size: 2, name: 'Config_Network_Transmit_Get', process: null, callback: null},
{id: 0x8024, size: 2, name: 'Config_Network_Transmit_Set', process: null, callback: null},
{id: 0x8025, size: 2, name: 'Config_Network_Transmit_Status', process: null, callback: null},
{id: 0x8026, size: 2, name: 'Config_Relay_Get', process: null, callback: null},
{id: 0x8027, size: 2, name: 'Config_Relay_Set', process: null, callback: null},
{id: 0x8028, size: 2, name: 'Config_Relay_Status', process: null, callback: null},
{id: 0x8029, size: 2, name: 'Config_SIG_Model_Subscription_Get', process: null, callback: null},
{id: 0x802A, size: 2, name: 'Config_SIG_Model_Subscription_List', process: null, callback: null},
{id: 0x802B, size: 2, name: 'Config_Vendor_Model_Subscription_Get', process: null, callback: null},
{id: 0x802C, size: 2, name: 'Config_Vendor_Model_Subscription_List', process: null, callback: null},
{id: 0x802D, size: 2, name: 'Config_Low_Power_Node_PollTimeout_Get', process: null, callback: null},
{id: 0x802E, size: 2, name: 'Config_Low_Power_Node_PollTimeout_Status', process: null, callback: null},
{id: 0x802F, size: 2, name: 'Health_Fault_Clear', process: null, callback: null},
{id: 0x8030, size: 2, name: 'Health_Fault_Clear_Unacknowledged', process: null, callback: null},
{id: 0x8031, size: 2, name: 'Health_Fault_Get', process: null, callback: null},
{id: 0x8032, size: 2, name: 'Health_Fault_Test', process: null, callback: null},
{id: 0x8033, size: 2, name: 'Health_Fault_Test_Unacknowledged', process: null, callback: null},
{id: 0x8034, size: 2, name: 'Health_Period_Get', process: null, callback: null},
{id: 0x8035, size: 2, name: 'Health_Period_Set', process: null, callback: null},
{id: 0x8036, size: 2, name: 'Health_Period_Set_Unacknowledged', process: null, callback: null},
{id: 0x8037, size: 2, name: 'Health_Period_Status', process: null, callback: null},
{id: 0x8038, size: 2, name: 'Config_Heartbeat_Publication_Get', process: null, callback: null},
{id: 0x8039, size: 2, name: 'Config_Heartbeat_Publication_Set', process: null, callback: null},
{id: 0x803A, size: 2, name: 'Config_Heartbeat_Subscription_Get', process: null, callback: null},
{id: 0x803B, size: 2, name: 'Config_Heartbeat_Subscription_Set', process: null, callback: null},
{id: 0x803C, size: 2, name: 'Config_Heartbeat_Subscription_Status', process: null, callback: null},
{id: 0x803D, size: 2, name: 'Config_Model_App_Bind', process: null, callback: null},
{id: 0x803E, size: 2, name: 'Config_Model_App_Status', process: null, callback: null},
{id: 0x803F, size: 2, name: 'Config_Model_App_Unbind', process: null, callback: null},
{id: 0x8040, size: 2, name: 'Config_NetKey_Add', process: null, callback: null},
{id: 0x8041, size: 2, name: 'Config_NetKey_Delete', process: null, callback: null},
{id: 0x8042, size: 2, name: 'Config_NetKey_Get', process: null, callback: null},
{id: 0x8043, size: 2, name: 'Config_NetKey_List', process: null, callback: null},
{id: 0x8044, size: 2, name: 'Config_NetKey_Status', process: null, callback: null},
{id: 0x8045, size: 2, name: 'Config_NetKey_Update', process: null, callback: null},
{id: 0x8046, size: 2, name: 'Config_Node_Identity_Get', process: null, callback: null},
{id: 0x8047, size: 2, name: 'Config_Node_Identity_Set', process: null, callback: null},
{id: 0x8048, size: 2, name: 'Config_Node_Identity_Status', process: null, callback: null},
{id: 0x8049, size: 2, name: 'Config_Node_Reset', process: null, callback: null},
{id: 0x804A, size: 2, name: 'Config_Node_Reset_Status', process: null, callback: null},
{id: 0x804B, size: 2, name: 'Config_SIG_Model_App_Get', process: null, callback: null},
{id: 0x804C, size: 2, name: 'Config_SIG_Model_App_List', process: null, callback: null},
{id: 0x804D, size: 2, name: 'Config_Vendor_Model_App_Get', process: null, callback: null},
{id: 0x804E, size: 2, name: 'Config_Vendor_Model_App_List', process: null, callback: null},
];

OPCODE.FindByName = function (opcode_name) {
  var obj = OPCODE.find(function (obj) {
    return obj.name == opcode_name;
  });
  return obj;
};
OPCODE.FindByID = function (id) {
  var obj = OPCODE.find(function (obj) {
    return obj.id == id;
  });
  return obj;
};

OPCODE.ToHexID = function (obj) {
  return utils.toHex(obj.id, obj.size);
};
